"""Import selected Phase 3.5 Word sources into static JavaScript data files.

Development-only utility. It is not used by the React production bundle.
"""

from __future__ import annotations

import argparse
import json
import re
import unicodedata
from pathlib import Path

from docx import Document


VOCABULARY_DOCUMENT = "fase_3_5_vocabulary_practice_work_vocabulary.docx"
TYPING_DOCUMENT = "fase_3_5_typing_test_reference_texts.docx"
LEVEL_ORDER = {"A1": 1, "A2": 2, "B1": 3, "B2": 4, "C1": 5}


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "-", normalized.lower()).strip("-")


def js_export(name: str, value: object) -> str:
    return f"export const {name} = {json.dumps(value, ensure_ascii=False, indent=2)}\n"


def module_level(levels: list[str]) -> str:
    unique = sorted(set(levels), key=lambda level: LEVEL_ORDER.get(level, 99))
    if not unique:
        return "Sin nivel"
    return unique[0] if len(unique) == 1 else f"{unique[0]}-{unique[-1]}"


def import_vocabulary(resources: Path, project: Path) -> dict[str, int]:
    source = resources / VOCABULARY_DOCUMENT
    document = Document(source)
    summary_rows = [[cell.text.strip() for cell in row.cells] for row in document.tables[0].rows[1:]]
    modules = []

    for index, summary in enumerate(summary_rows, start=1):
        category, declared_count, description, _quiz_note = summary
        slug = slugify(category)
        rows = [[cell.text.strip() for cell in row.cells] for row in document.tables[index].rows[1:]]
        terms = []
        for term_index, row in enumerate(rows, start=1):
            term, translation, definition, example, level, term_type = row
            terms.append(
                {
                    "id": f"vocab-{slug}-{term_index:03d}",
                    "term": term,
                    "translation": translation,
                    "definition": definition,
                    "example": example,
                    "exampleTranslation": "",
                    "difficulty": level,
                    "level": level,
                    "type": term_type,
                    "context": category,
                }
            )
        if len(terms) != int(declared_count):
            raise ValueError(f"{category}: expected {declared_count} terms, found {len(terms)}")
        levels = [term["level"] for term in terms]
        modules.append(
            {
                "id": slug,
                "title": category,
                "slug": slug,
                "description": description,
                "level": module_level(levels),
                "category": category,
                "tags": [category.lower(), "work vocabulary", "phase 3.5"],
                "terms": terms,
            }
        )

    metadata = {
        "id": "phase-3-5-work-vocabulary",
        "name": "Work Vocabulary Modules",
        "sourceDocument": VOCABULARY_DOCUMENT,
        "moduleCount": len(modules),
        "termCount": sum(len(module["terms"]) for module in modules),
    }
    output = "// Generated by scripts/import_phase35_sources.py from the Word source.\n\n"
    output += js_export("workVocabularyMetadata", metadata) + "\n"
    output += js_export("workVocabularyModules", modules) + "\n"
    output += "export const workVocabularyCategories = [...new Set(workVocabularyModules.map((module) => module.category))]\n"
    output += "export const workVocabularyLevels = [...new Set(workVocabularyModules.map((module) => module.level))]\n"
    (project / "src/data/workVocabularyModules.js").write_text(output, encoding="utf-8", newline="\n")
    return {"modules": len(modules), "terms": metadata["termCount"]}


def paragraphs_between(paragraphs: list[str], start_marker: str, end_marker: str) -> list[str]:
    start = paragraphs.index(start_marker)
    reference_index = paragraphs.index("Texto de referencia:", start)
    end = paragraphs.index(end_marker, reference_index + 1)
    return paragraphs[reference_index + 1 : end]


def import_typing(resources: Path, project: Path) -> dict[str, object]:
    source = resources / TYPING_DOCUMENT
    document = Document(source)
    paragraphs = [paragraph.text.strip() for paragraph in document.paragraphs if paragraph.text.strip()]
    specifications = [
        ("Texto 1 - Facil", "Texto 2 - Intermedio", "typing_easy_b1", "General Work Facts", "Easy", "B1 aproximado", "Trabajo general y comunicación clara"),
        ("Texto 2 - Intermedio", "Texto 3 - Dificil", "typing_medium_b1_b2", "Modern Written Work", "Intermediate", "B1-B2 aproximado", "Comunicación escrita, servicio y call center"),
        ("Texto 3 - Dificil", "Notas para implementacion en Codex", "typing_hard_c1", "Advanced Professional Documentation", "Hard", "C1 preliminar aproximado", "Documentación técnica y operaciones"),
    ]
    passages = []
    for start, end, identifier, title, difficulty, level, context in specifications:
        text = "\n\n".join(paragraphs_between(paragraphs, start, end))
        passages.append(
            {
                "id": identifier,
                "slug": identifier.replace("_", "-"),
                "title": title,
                "category": "Typing Reference Text",
                "level": level,
                "context": context,
                "text": text,
                "difficulty": difficulty,
                "wordCount": len(re.findall(r"[A-Za-z0-9]+(?:['-][A-Za-z0-9]+)?", text)),
            }
        )

    metadata = {
        "id": "phase-3-5-typing-reference-texts",
        "name": "Typing Test Reference Texts",
        "sourceDocument": TYPING_DOCUMENT,
        "passageCount": len(passages),
    }
    output = "// Generated by scripts/import_phase35_sources.py from the Word source.\n\n"
    output += js_export("typingTestMetadata", metadata) + "\n"
    output += js_export("typingTestPassages", passages) + "\n"
    output += "export const typingTestDifficulties = ['Easy', 'Intermediate', 'Hard']\n"
    (project / "src/data/typingTestPassages.js").write_text(output, encoding="utf-8", newline="\n")
    return {"passages": len(passages), "wordCounts": [passage["wordCount"] for passage in passages]}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--resources", type=Path, required=True)
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    result = {
        "vocabulary": import_vocabulary(args.resources, args.project),
        "typing": import_typing(args.resources, args.project),
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
